// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr_DaOrBlAlHsqO_S390hugpYen4RcEI8',
    appId: '1:979233594639:web:757d1a42d075526b3d727a',
    messagingSenderId: '979233594639',
    projectId: 'eproject-4fbc1',
    authDomain: 'eproject-4fbc1.firebaseapp.com',
    storageBucket: 'eproject-4fbc1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI6I3yfCpJpKq4XGGcjiQc3C1mTTz8-QE',
    appId: '1:979233594639:android:de10349e153bf62c3d727a',
    messagingSenderId: '979233594639',
    projectId: 'eproject-4fbc1',
    storageBucket: 'eproject-4fbc1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJlVYb8okajKx1pnDO1Swo2KzfqJweqLk',
    appId: '1:979233594639:ios:6a1fd8db0344db2d3d727a',
    messagingSenderId: '979233594639',
    projectId: 'eproject-4fbc1',
    storageBucket: 'eproject-4fbc1.firebasestorage.app',
    iosBundleId: 'com.example.eproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJlVYb8okajKx1pnDO1Swo2KzfqJweqLk',
    appId: '1:979233594639:ios:6a1fd8db0344db2d3d727a',
    messagingSenderId: '979233594639',
    projectId: 'eproject-4fbc1',
    storageBucket: 'eproject-4fbc1.firebasestorage.app',
    iosBundleId: 'com.example.eproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr_DaOrBlAlHsqO_S390hugpYen4RcEI8',
    appId: '1:979233594639:web:52c0647396f6f5cc3d727a',
    messagingSenderId: '979233594639',
    projectId: 'eproject-4fbc1',
    authDomain: 'eproject-4fbc1.firebaseapp.com',
    storageBucket: 'eproject-4fbc1.firebasestorage.app',
  );
}
